controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

home:
    path: /
    controller: App\Controller\HomeController::index
blog:
    path: /blog
    controller: App\Controller\BlogController::index
blog_show:
    path: /blog/{id}
    controller: App\Controller\BlogController::show